### ISSUE TITLE
Causes problems with Craftory Tech v0.9.0

### ISSUE THREAD

**Issue by Rob-Fox** [TonimatasDEV/PerWorldPlugins#10]
When trying to run on a server with PaperMC 1.17.1 and Craftory Tech v0.9.0 errors are generated with relation to protectionManager:
`[09:41:36] [Server thread/ERROR]: Cannot invoke "tech.brettsaunders.craftory.external.dough.protection.ProtectionManager.hasPermission(org.bukkit.OfflinePlayer, org.bukkit.block.Block, tech.brettsaunders.craftory.external.dough.protection.Interaction)" because "tech.brettsaunders.craftory.Craftory.protectionManager" is null
java.lang.NullPointerException: Cannot invoke "tech.brettsaunders.craftory.external.dough.protection.ProtectionManager.hasPermission(org.bukkit.OfflinePlayer, org.bukkit.block.Block, tech.brettsaunders.craftory.external.dough.protection.Interaction)" because "tech.brettsaunders.craftory.Craftory.protectionManager" is null
	at tech.brettsaunders.craftory.api.blocks.CustomBlockManagerEvents.onCustomBlockInteract(CustomBlockManagerEvents.java:328) ~[Craftory-0.9.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-411]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
	at tech.brettsaunders.craftory.api.sentry.LoggedPluginManager$1.callEvent(LoggedPluginManager.java:75) ~[Craftory-0.9.0.jar:?]
	at net.tonimatasdev.perworldplugins.listener.RegisteredListener.callEvent(RegisteredListener.java:18) ~[PerWorldPlugins-1.0.1.9.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:221) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1739) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by TonimatasDEV** [comment]
> When trying to run on a server with PaperMC 1.17.1 and Craftory Tech v0.9.0 errors are generated with relation to protectionManager: `[09:41:36] [Server thread/ERROR]: Cannot invoke "tech.brettsaunders.craftory.external.dough.protection.ProtectionManager.hasPermission(org.bukkit.OfflinePlayer, org.bukkit.block.Block, tech.brettsaunders.craftory.external.dough.protection.Interaction)" because "tech.brettsaunders.craftory.Craftory.protectionManager" is null java.lang.NullPointerException: Cannot invoke "tech.brettsaunders.craftory.external.dough.protection.ProtectionManager.hasPermission(org.bukkit.OfflinePlayer, org.bukkit.block.Block, tech.brettsaunders.craftory.external.dough.protection.Interaction)" because "tech.brettsaunders.craftory.Craftory.protectionManager" is null at tech.brettsaunders.craftory.api.blocks.CustomBlockManagerEvents.onCustomBlockInteract(CustomBlockManagerEvents.java:328) ~[Craftory-0.9.0.jar:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-411] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411] at tech.brettsaunders.craftory.api.sentry.LoggedPluginManager$1.callEvent(LoggedPluginManager.java:75) ~[Craftory-0.9.0.jar:?] at net.tonimatasdev.perworldplugins.listener.RegisteredListener.callEvent(RegisteredListener.java:18) ~[PerWorldPlugins-1.0.1.9.jar:?] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411] at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Paper-411] at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[patched_1.17.1.jar:git-Paper-411] at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:221) ~[app:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1739) ~[app:?] at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?] at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Sorry, PerWorldPlugins is temporarily abandoned due to instability and lack of compatibility with other plugins
