### ISSUE TITLE
spam in console

### ISSUE THREAD

**Issue by games4681** [TonimatasDEV/PerWorldPlugins#18]
[ERROR] .... Could not pass event PlayerMoveEvent to PerWorldPlugins v1.3.3

java.lang.IllegalStateException: zip file closed

at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]

at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]

at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]

at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]

at net.advancedplugins.pets.abilities.effects.FreezeEffect$SpigotListener.onPlayerMove(FreezeEffect.java:26) ~[AdvancedPets-2.1.0.jar:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor659.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at net.tonimatasdev.perworldplugins.util.ListenerUtils.perWorldPlugins(ListenerUtils.java:47) ~[PerWorldPlugins-1.3.3.jar:?]

at net.tonimatasdev.perworldplugins.listener.PlayerEvents.onMove(PlayerEvents.java:158) ~[PerWorldPlugins-1.3.3.jar:?]

at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]

at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TonimatasDEV** [comment]
Test this version: 
[PerWorldPlugins-1.3.4.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/11071942/PerWorldPlugins-1.3.4.zip)

**Comment by games4681** [comment]
you fixed the errors i send in your discord server? with the chat errors and events problems happening because of the plugin?

**Comment by TonimatasDEV** [comment]
> you fixed the errors i send in your discord server? with the chat errors and events problems happening because of the plugin?

Yes

**Comment by TonimatasDEV** [comment]
> you fixed the errors i send in your discord server? with the chat errors and events problems happening because of the plugin?

If you have any problems reopen the issue

**Comment by games4681** [comment]
when you upload the new update to spigotmc?
