### ISSUE TITLE
Bug with RealisticSeasons

### ISSUE THREAD

**Issue by appleLPG** [TonimatasDEV/PerWorldPlugins#26]
Add RealisticSeasons-10.7.0.jar
Add ProtocolLib.jar
Add PerWorldPlugins-1.5.0.jar
Start the server
[PerWorldPlugins] Converted all Listeners/Commands correctly.
[18:36:18] [Server thread/WARN]: [RealisticSeasons] Task #4 for RealisticSeasons v10.7.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getCommand(String)" is null
        at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:242) ~[?:?]
        at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:163) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1256) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

Run RealisticSeasons command No response
spigot-1.20.1

**Comment by TonimatasDEV** [comment]
> Add RealisticSeasons-10.7.0.jar Add ProtocolLib.jar Add PerWorldPlugins-1.5.0.jar Start the server [PerWorldPlugins] Converted all Listeners/Commands correctly. [18:36:18] [Server thread/WARN]: [RealisticSeasons] Task #4 for RealisticSeasons v10.7.0 generated an exception java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getCommand(String)" is null at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:242) ~[?:?] at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:163) ~[?:?] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1256) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b] at java.lang.Thread.run(Thread.java:842) ~[?:?]
> 
> Run RealisticSeasons command No response spigot-1.20.1

**Test this version:** [PerWorldPlugins-1.5.1.zip](https://github.com/TonimatasDEV/PerWorldPlugins/files/13686325/PerWorldPlugins-1.5.1.zip)

**Comment by appleLPG** [comment]
Thanks Fixed
