### ISSUE TITLE
Command related issues

### ISSUE THREAD

**Issue by ApliNi** [TonimatasDEV/PerWorldPlugins#29]
Hello, I discovered some problems after updating from `PerWorldPlugins-1.5.3` to the latest version. Some plug-in commands will generate an error after being entered, but they can be used normally, while some commands will be blocked even if the default configuration is used.

As shown in the log
- An error occurred when using the `/c` command of the ChestCommands plugin, but the corresponding menu could be opened normally.
- When using the command alias `/b` created through `commands.yml`, it is blocked and a disabledCommandMessage is output. But the `/back` command corresponding to the alias can be used normally.

At the same time, these errors will not appear on the old version of `PerWorldPlugins-1.5.3`.

I hope you can help me check these issues, thanks. Please let me know if I need to provide anything.

Edit: Later I also discovered that `/gamemode creative` would also be blocked, displaying disabledCommandMessage.

This is a minimal log:
```
Java HotSpot(TM) 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
[12:51:19 INFO]: System Info: Java 22 (Java HotSpot(TM) 64-Bit Server VM 22.0.2+9-jvmci-b01) Host: Windows 10 10.0 (amd64)
[12:51:19 INFO]: Loading libraries, please wait...
[12:51:20 WARN]: [oshi.driver.windows.perfmon.PerfmonDisabled] Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[12:51:27 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[12:51:29 INFO]: Loaded 1196 recipes
[12:51:29 INFO]: Loaded 1339 advancements
[12:51:30 INFO]: Starting minecraft server version 1.20.4
[12:51:30 INFO]: Loading properties
[12:51:30 WARN]: An expected class  org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler$4 was not found for preloading: org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler$4
[12:51:30 INFO]: This server is running Leaf version git-Leaf-"7563d69" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7563d69 on ver/1.20.4)
[12:51:31 INFO]: Server Ping Player Sample Count: 0
[12:51:31 INFO]: Using 8 threads for Netty based IO
[12:51:31 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[12:51:31 INFO]: Default game type: SURVIVAL
[12:51:31 INFO]: Generating keypair
[12:51:31 INFO]: Starting Minecraft server on *:25565
[12:51:31 INFO]: Using default channel type
[12:51:31 INFO]: Paper: Using Java compression from Velocity.
[12:51:31 INFO]: Paper: Using Java cipher from Velocity.
[12:51:32 INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.3
[12:51:32 INFO]: [ViaVersion] ViaVersion 5.0.3 is now loaded. Registering protocol transformers and injecting...
[12:51:32 INFO]: [ViaVersion] Loading block connection mappings ...
[12:51:32 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[12:51:32 INFO]: [ViaBackwards] Loading translations...
[12:51:32 INFO]: [ViaBackwards] Registering protocols...
[12:51:33 INFO]: [spark] Loading server plugin spark v1.10.97
[12:51:33 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v5.0.3
[12:51:33 INFO]: [PerWorldPlugins] Loading server plugin PerWorldPlugins v1.5.6
[12:51:33 INFO]: [PerWorldPlugins] Enabling PerWorldPlugins v1.5.6
[12:51:33 INFO]: <---------------------------------------->
[12:51:33 INFO]: PerWorldPlugins 1.5.6 has been enabled.
[12:51:33 INFO]: <---------------------------------------->
[12:51:33 INFO]: [HuskHomes] Loading server plugin HuskHomes v4.5.5-77c115a
[12:51:33 INFO]: [ChestCommands] Loading server plugin ChestCommands v4.0.4
[12:51:33 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[12:51:33 WARN]: The server will make no attempt to authenticate usernames. Beware.
[12:51:33 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[12:51:33 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[12:51:33 INFO]: Preparing level "world"
[12:51:34 INFO]: [ViaVersion] Enabling ViaVersion v5.0.3
[12:51:34 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.3-1.20.4 (765)
[12:51:34 INFO]: [spark] Enabling spark v1.10.97
[12:51:35 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[12:51:35 INFO]: [spark] Starting background profiler...
[12:51:35 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[12:51:35 INFO]: [ViaBackwards] Enabling ViaBackwards v5.0.3
[12:51:35 INFO]: [HuskHomes] Enabling HuskHomes v4.5.5-77c115a
[12:51:35 INFO]: [HuskHomes] Initializing plugin config & locale files...
[12:51:35 INFO]: [HuskHomes] Successfully initialized plugin config & locale files
[12:51:35 INFO]: [HuskHomes] Initializing SQLite database connection...
[12:51:35 INFO]: [HuskHomes] Successfully initialized SQLite database connection
[12:51:35 INFO]: [HuskHomes] Initializing hooks...
[12:51:35 INFO]: [HuskHomes] Successfully initialized hooks
[12:51:35 INFO]: [HuskHomes] Initializing events...
[12:51:35 INFO]: [HuskHomes] Successfully initialized events
[12:51:35 INFO]: [HuskHomes] Initializing commands...
[12:51:35 INFO]: [HuskHomes] Successfully initialized commands
[12:51:35 INFO]: [HuskHomes] Initializing API...
[12:51:35 INFO]: [HuskHomes] Successfully initialized API
[12:51:35 INFO]: [HuskHomes] Initializing metrics...
[12:51:35 INFO]: [HuskHomes] Successfully initialized metrics
[12:51:35 INFO]: [ChestCommands] Enabling ChestCommands v4.0.4
[12:51:35 WARN]: [ChestCommands] Couldn't find Vault and a compatible economy plugin! Money-related features will not work.
[12:51:35 INFO]: JMX monitoring enabled
[12:51:35 INFO]: Running delayed init tasks
[12:51:35 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[12:51:35 INFO]: [PerWorldPlugins] Converted all Listeners correctly.
[12:51:35 INFO]: Done (5.823s)! For help, type "help"
[12:51:36 INFO]: [ChestCommands] Found a new version: v4.0.5 (yours: v4.0.4)
[12:51:36 INFO]: [ChestCommands] Download the update on Bukkit Dev:
[12:51:36 INFO]: [ChestCommands] https://dev.bukkit.org/projects/chest-commands
[12:51:40 INFO]: UUID of player ApliNi is a1d1c2cd-42e5-394d-961a-8ee6680df4f8
[12:51:41 INFO]: ApliNi joined the game
[12:51:41 INFO]: ApliNi[/127.0.0.1:46273] logged in with entity id 1 at ([world]-28.08715893196928, 63.9375, 38.36184155647584)
[12:51:44 INFO]: ApliNi issued server command: /c
[12:51:44 ERROR]: Could not pass event PlayerCommandPreprocessEvent to PerWorldPlugins v1.5.6
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:365) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:428) ~[?:?]
        at PerWorldPlugins-1.5.6.jar/dev.tonimatas.perworldplugins.listener.Listeners.onCommandPreProcess(Listeners.java:70) ~[PerWorldPlugins-1.5.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2279) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1466) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1444) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[12:51:45 INFO]: ApliNi issued server command: /b
>
```

**Comment by TonimatasDEV** [comment]
I'm fixing it.

**Comment by TonimatasDEV** [comment]
Sorry for the late. Try this version:
[PerWorldPlugins-1.5.7.zip](https://github.com/user-attachments/files/16907208/PerWorldPlugins-1.5.7.zip)

**Comment by ApliNi** [comment]
```
[10:31:26 INFO]: ApliNi issued server command: /c
[10:31:29 INFO]: ApliNi issued server command: /b
[10:31:29 WARN]: [PerWorldPlugins] ViaVersion
[10:31:29 WARN]: [PerWorldPlugins] HuskHomes
[10:31:29 WARN]: [PerWorldPlugins] ChestCommands
[10:31:29 WARN]: [PerWorldPlugins] InvisibleFrames
[10:31:57 INFO]: ApliNi issued server command: /back
[10:31:57 WARN]: [PerWorldPlugins] ViaVersion
[10:31:57 WARN]: [PerWorldPlugins] HuskHomes
[10:31:57 WARN]: [PerWorldPlugins] ChestCommands
[10:31:57 WARN]: [PerWorldPlugins] InvisibleFrames
```

The current situation is this, I keep the configuration the same, `/c` is normal, `/b` is blocked, `/back` is normal

**Comment by TonimatasDEV** [comment]
@ApliNi Try it (It is from discord some people report related problems)

[PerWorldPlugins-1.5.7.dev.999.zip](https://github.com/user-attachments/files/16924553/PerWorldPlugins-1.5.7.dev.999.zip)

**Comment by ApliNi** [comment]
```
[10:24:52 INFO]: ApliNi issued server command: /gamemode creative
> op aplini
[10:25:06 INFO]: Nothing changed. The player already is an operator
[10:25:09 INFO]: ApliNi issued server command: /c
[10:25:10 INFO]: ApliNi issued server command: /b
[10:25:13 INFO]: ApliNi issued server command: /back
```
The situation in this version seems to be the same as before. Keep the configuration unchanged, `/gamemode creative`, `/b` cannot be used

**Comment by TonimatasDEV** [comment]
@ApliNi Try the stable 1.5.7 release: https://modrinth.com/plugin/perworldplugins/version/1.5.7

**Comment by ApliNi** [comment]
> @ApliNi Try this dev version 1.5.8. I rewrote the block command system.
> 
> [PerWorldPlugins-1.5.8.zip](https://github.com/user-attachments/files/16944581/PerWorldPlugins-1.5.8.zip)

The `/gamemode creative` command has resumed normal functionality, but command aliases created through `commands.yml` are being intercepted.

**Comment by TonimatasDEV** [comment]
@ApliNi I reworked PerWorldPlugins again test the latest version 1.5.9

**Comment by ApliNi** [comment]
> @ApliNi I reworked PerWorldPlugins again test the latest version 1.5.9

This version seems to be working fine. I will install it on the server for testing. If there is no problem, I will close this issue. Thank you for your support.
